[package]
name = "programming_contest_rust"
version = "0.1.0"
authors = ["Katsuya Kikuchi <k.kikuchi.ah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = {version = "0.4.1", features = ["derive"] }

[[bin]]
name = "t"
path = "src/VirtualContest/20200830/T.rs"
[[bin]]
name = "u"
path = "src/VirtualContest/20200830/U.rs"
[[bin]]
name = "v"
path = "src/VirtualContest/20200830/V.rs"