[package]
name = "programming_contest_rust"
version = "0.1.0"
authors = ["Katsuya Kikuchi <k.kikuchi.ah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.1"

[[bin]]
name = "a"
path = "src/AtCoder Beginner Contest/ABC125/a.rs"
[[bin]]
name = "b"
path = "src/AtCoder Beginner Contest/ABC125/b.rs"
[[bin]]
name = "c"
path = "src/AtCoder Beginner Contest/ABC125/c.rs"
[[bin]]
name = "d"
path = "src/AtCoder Beginner Contest/ABC125/d.rs"