[package]
name = "programming_contest_rust"
version = "0.1.0"
authors = ["Katsuya Kikuchi <k.kikuchi.ah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = {version = "0.4.1", features = ["derive"] }

[[bin]]
name = "a"
path = "src/VirtualContest/20200830/027.rs"
[[bin]]
name = "b"
path = "src/VirtualContest/20200830/028.rs"
[[bin]]
name = "c"
path = "src/VirtualContest/20200830/029.rs"
[[bin]]
name = "d"
path = "src/VirtualContest/20200830/030.rs"