[package]
name = "programming_contest_rust"
version = "0.1.0"
authors = ["Katsuya Kikuchi <k.kikuchi.ah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = {version = "0.4.1", features = ["derive"] }

[[bin]]
name = "w"
path = "src/VirtualContest/20200830/W.rs"
[[bin]]
name = "x"
path = "src/VirtualContest/20200830/X.rs"
[[bin]]
name = "y"
path = "src/VirtualContest/20200830/Y.rs"
[[bin]]
name = "z"
path = "src/VirtualContest/20200830/Z.rs"