[package]
name = "programming_contest_rust"
version = "0.1.0"
authors = ["Katsuya Kikuchi <k.kikuchi.ah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = {version = "0.4.1", features = ["derive"] }
ordered-float = "2.0.0"

[[bin]]
name = "a"
path = "src/VirtualContest/graph/041.rs"
[[bin]]
name = "b"
path = "src/VirtualContest/graph/042.rs"
[[bin]]
name = "c"
path = "src/VirtualContest/graph/043.rs"
[[bin]]
name = "d"
path = "src/VirtualContest/graph/044.rs"
[[bin]]
name = "e"
path = "src/VirtualContest/graph/045.rs"