[package]
name = "programming_contest_rust"
version = "0.1.0"
authors = ["Katsuya Kikuchi <k.kikuchi.ah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = {version = "0.4.1", features = ["derive"] }


[[bin]]
name = "a1"
path = "src/AtCoder Typical Contest/ATC001/A.rs"
[[bin]]
name = "b1"
path = "src/AtCoder Typical Contest/ATC001/B.rs"
[[bin]]
name = "a2"
path = "src/AtCoder Typical Contest/ATC002/A.rs"
[[bin]]
name = "b2"
path = "src/AtCoder Typical Contest/ATC002/B.rs"
[[bin]]
name = "c2"
path = "src/AtCoder Typical Contest/ATC001/C.rs"