[package]
name = "programming_contest_rust"
version = "0.1.0"
authors = ["Katsuya Kikuchi <k.kikuchi.ah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = {version = "0.4.1", features = ["derive"] }
ordered-float = "2.0.0"
clippy = "0.0.302"

[[bin]]
name = "a"
path = "src/VirtualContest/dp/026.rs"
[[bin]]
name = "b"
path = "src/VirtualContest/dp/027.rs"
[[bin]]
name = "c"
path = "src/VirtualContest/dp/028.rs"
[[bin]]
name = "d"
path = "src/VirtualContest/dp/029.rs"
[[bin]]
name = "e"
path = "src/VirtualContest/dp/030.rs"
