[package]
name = "programming_contest_rust"
version = "0.1.0"
authors = ["Katsuya Kikuchi <k.kikuchi.ah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = {version = "0.4.1", features = ["derive"] }

[[bin]]
name = "a"
path = "src/AtCoder Beginner Contest/ABC126/A.rs"
[[bin]]
name = "b"
path = "src/AtCoder Beginner Contest/ABC126/B.rs"
[[bin]]
name = "c"
path = "src/AtCoder Beginner Contest/ABC126/C.rs"
[[bin]]
name = "d"
path = "src/AtCoder Beginner Contest/ABC126/D.rs"
[[bin]]
name = "e"
path = "src/AtCoder Beginner Contest/ABC126/E.rs"
[[bin]]
name = "f"
path = "src/AtCoder Beginner Contest/ABC126/F.rs"