[package]
name = "programming_contest_rust"
version = "0.1.0"
authors = ["Katsuya Kikuchi <k.kikuchi.ah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = {version = "0.4.1", features = ["derive"] }

[[bin]]
name = "k"
path = "src/VirtualContest/20200830/K.rs"
[[bin]]
name = "l"
path = "src/VirtualContest/20200830/L.rs"
[[bin]]
name = "m"
path = "src/VirtualContest/20200830/M.rs"