[package]
name = "programming_contest_rust"
version = "0.1.0"
authors = ["Katsuya Kikuchi <k.kikuchi.ah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.1"

[[bin]]
name = "a"
path = "src/AizuOnlineJudge/ITP1/5_A.rs"
[[bin]]
name = "b"
path = "src/AizuOnlineJudge/ITP1/5_B.rs"
[[bin]]
name = "c"
path = "src/AizuOnlineJudge/ITP1/5_C.rs"
[[bin]]
name = "d"
path = "src/AizuOnlineJudge/ITP1/5_D.rs"
[[bin]]
name = "aa"
path = "src/AizuOnlineJudge/ITP1/6_A.rs"
[[bin]]
name = "bb"
path = "src/AizuOnlineJudge/ITP1/6_B.rs"
[[bin]]
name = "cc"
path = "src/AizuOnlineJudge/ITP1/6_C.rs"
[[bin]]
name = "dd"
path = "src/AizuOnlineJudge/ITP1/6_D.rs"